[package]
name = "catr"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
clap = "4.1.4"
assert_cmd = "2.0.8"
predicates = "2.1.5"
rand = "0.8.5"